services:
  zetaapi:
    container_name: zetaapi
    image: jonas/nestjs
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: .
        target: /app
